# Generated by Django 6.0.6 on 2026-06-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('strokeColor', models.CharField(max_length=50)),
                ('strokeWidth', models.FloatField(default=2.0)),
                ('rawCoordinates', models.JSONField()),
            ],
        ),
    ]
